import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { createRecipeApprovalReview } from "../app/components/console/dialogs/recipe-approval-review";
import type { APIIntegration, APIRecipe, APIRecipeRevision } from "../app/lib/api";

const revision = {
  id: "recipe_revision_7",
  recipe_id: "recipe_1",
  revision: 7,
  spec_version: 2,
  spec: {
    schema_version: 2,
    integration_id: "integration_payments",
    title: "Read a payment",
    outcome: "The application reads one payment.",
    capability_ids: ["payments.read"],
    prerequisites: [],
    steps: [],
    checks: [],
  },
  markdown: "# Read a payment",
  references: [],
  validation: [],
  generated_by: "ai",
  model: "gpt-review",
  integration_revision_id: "integration_revision_3",
  integration_manifest_hash: "sha256:manifest",
  prompt_version: "recipe.authoring:4",
  prompt_hash: "sha256:prompt",
  created_by: "user_1",
  created_at: "2026-08-26T00:00:00Z",
} as unknown as APIRecipeRevision;

const integration = {
  id: "integration_payments",
  display_name: "Payments API",
} as unknown as APIIntegration;

function recipe(currentRevisionID: string, currentRevision: APIRecipeRevision | undefined): APIRecipe {
  return {
    id: "recipe_1",
    integration_id: "integration_payments",
    current_revision_id: currentRevisionID,
    current_revision: currentRevision,
  } as unknown as APIRecipe;
}

test("approval review is pinned to the exact current revision and its integration", () => {
  const review = createRecipeApprovalReview(recipe(revision.id, revision), [integration]);
  assert.ok(review);
  assert.equal(review.currentRevisionID, revision.id);
  assert.equal(review.revision, revision);
  assert.equal(review.integration, integration);
});

test("approval review fails closed for mismatched or missing current revision data", () => {
  assert.equal(createRecipeApprovalReview(recipe("recipe_revision_8", revision), [integration]), null);
  assert.equal(createRecipeApprovalReview(recipe(revision.id, undefined), [integration]), null);
  assert.equal(createRecipeApprovalReview({ ...recipe(revision.id, revision), id: "recipe_2" } as APIRecipe, [integration]), null);
  const mismatchedIntegrationRevision = {
    ...revision,
    spec: { ...revision.spec, integration_id: "integration_other" },
  } as APIRecipeRevision;
  assert.equal(createRecipeApprovalReview(recipe(mismatchedIntegrationRevision.id, mismatchedIntegrationRevision), [integration]), null);
});

test("recipe approval is exposed only from the exact-revision review dialog", async () => {
  const view = await readFile(new URL("../app/components/console/catalog-settings-views.tsx", import.meta.url), "utf8");
  const dialog = await readFile(new URL("../app/components/console/dialogs/recipe-approval-dialog.tsx", import.meta.url), "utf8");
  const review = await readFile(new URL("../app/components/console/dialogs/recipe-approval-review.ts", import.meta.url), "utf8");
  const styles = await readFile(new URL("../app/styles/console-catalog.css", import.meta.url), "utf8");

  assert.match(view, /const approvalCandidate = createRecipeApprovalReview\(recipe, integrations\)/);
  assert.match(view, /setApprovalReview\(approvalCandidate\)/);
  assert.doesNotMatch(view, /onClick=\{[^}]*onApprove/);
  assert.match(review, /revision\.id !== recipe\.current_revision_id/);
  assert.match(dialog, /await onApprove\(recipe\)/);
  assert.match(dialog, /Approve revision \$\{revision\.revision\}/);

  for (const label of [
    "Canonical Markdown",
    "Current revision ID",
    "Integration revision ID",
    "Integration manifest hash",
    "Generated by",
    "Model",
    "Prompt version",
    "Prompt hash",
    "Validation findings",
    "References",
    "Revision number",
  ]) {
    assert.match(dialog, new RegExp(label));
  }
  assert.match(styles, /\.dialog-panel:has\(\.recipe-approval-review\)/);
  assert.match(dialog, /role="region" aria-label=\{`Canonical Markdown/);
});
