import { deUI } from "./ui/de";

export const de = {
  metadata: { title: "DokoSoko — Steuerzentrale für Agentenbereitstellung", description: "Konfigurieren Sie vertrauenswürdiges API-Wissen, Werkzeuge, Kundenidentität und MCP-Zugriff in einer Konsole." },
  languages: { label: "Sprache", select: "Sprache auswählen", en: "English", es: "Español", fr: "Français", de: "Deutsch", ja: "日本語", uk: "Українська", ptBR: "Português (Brasil)" },
  theme: { darkMode: "Dunkelmodus", switchToLight: "Zum hellen Modus wechseln", switchToDark: "Zum dunklen Modus wechseln", label: "Design", select: "Design auswählen", light: "Hell", dark: "Dunkel", system: "System", current: "Design: {{theme}}", controlHint: "Design {{theme}}. Klicken zum Wechseln; gedrückt halten für Optionen." },
  navigation: { main: "Hauptnavigation", sectionLabel: "Bereiche von {{name}}", consoleSection: "Konsolenbereich", deployment: "Bereitstellung", apis: "APIs", docs: "Dokumentation", sdksAndPackages: "SDKs und Pakete", identity: "Identität", tools: "Werkzeuge", recipes: "Rezepte", agentAccess: "Agentenzugriff", supportOutbox: "Support-Ausgang", settings: "Einstellungen", sources: "Quellen", documents: "Dokumente", apiContracts: "API-Verträge", queryLab: "Abfragelabor", packages: "Pakete", customerSignIn: "Kundenanmeldung", customerAccounts: "Kundenkonten", catalog: "Katalog", connections: "Verbindungen", mcpPreview: "MCP-Vorschau" },
  account: { defaultName: "Yuriy", defaultAdminName: "Yuriy Administrator", rootAdministrator: "Root-Administrator", platformAdmin: "Plattformadministrator", signOut: "Abmelden" },
  common: { skipToContent: "Zum Inhalt springen", reload: "Neu laden", retry: "Erneut versuchen", close: "Schließen", save: "Speichern", cancel: "Abbrechen", loading: "Wird geladen…", saving: "Wird gespeichert…", creating: "Wird erstellt…", verifying: "Wird überprüft…", copied: "Kopiert", notAvailable: "Nicht verfügbar", notSpecified: "Nicht angegeben", none: "Keine", all: "Alle", public: "Öffentlich", private: "Privat", global: "Global", combined: "Kombiniert", contract: "Vertrag", execution: "Ausführung", authorization: "Autorisierung", tests: "Tests", usage: "Nutzung", files: "Dateien", symbols: "Symbole", samples: "Beispiele", map: "Karte", diagnostics: "Diagnose", usedByApis: "Von APIs verwendet", members: "Mitglieder", manifest: "Manifest", review: "Prüfung", operations: "Operationen", schemas: "Schemas", examples: "Beispiele", normalized: "Normalisiert", aiAssist: "KI-Unterstützung", import: "Importieren", manual: "Manuell", detail: "Details", sections: "Abschnitte", runStatus: "Ausführungsstatus", active: "Aktiv", archived: "Archiviert" },
  enumLabels: { active: "Aktiv", archived: "Archiviert", attached: "Verknüpft", cancelled: "Abgebrochen", critical: "Kritisch", deprecated: "Veraltet", detached: "Getrennt", draft: "Entwurf", excluded: "Ausgeschlossen", failed: "Fehlgeschlagen", high: "Hoch", included: "Eingeschlossen", low: "Niedrig", medium: "Mittel", needsReview: "Prüfung erforderlich", partial: "Teilweise", published: "Veröffentlicht", quarantined: "Unter Quarantäne", queued: "In Warteschlange", ready: "Bereit", retired: "Stillgelegt", review: "In Prüfung", reviewReady: "Prüfbereit", running: "Wird ausgeführt", suspended: "Gesperrt", valid: "Gültig", validated: "Validiert", yanked: "Zurückgezogen", metadataOnly: "Nur Metadaten", resolvedSource: "Aufgelöste Quelle", sourcePublication: "Quellveröffentlichung", document: "Dokument", section: "Abschnitt", unknown: "Unbekannt ({{value}})" },
  format: { dateTime: "{{value, datetime}}", date: "{{value, datetime(year: numeric; month: short; day: numeric)}}", time: "{{value, datetime(hour: numeric; minute: 2-digit)}}", number: "{{value, number}}" },
  routes: { quickStart: "Schnellstart", resources: "Ressourcen", keysAccess: "Schlüssel und Zugriff", tools: "Werkzeuge", test: "Test", history: "Verlauf", documentation: "Dokumentation", apiContracts: "API-Verträge", sdks: "SDKs", overview: "Übersicht", tenantSettings: "Mandanteneinstellungen", configuration: "Konfiguration", aiConfiguration: "KI-Konfiguration", rootAccess: "Root-Zugriff" },
  tenantSettings: { overviewDescription: "Name, Slug, Beschreibung und Mandantenkennungen.", profileTitle: "Mandantenprofil", profileDescription: "Aktualisieren Sie die Mandantendaten, die in der Konsole und der MCP-Einrichtung angezeigt werden.", name: "Mandantenname", nameHint: "Wird im Konsolenkopf und auf kundenorientierten MCP-Schaltflächen angezeigt.", slug: "Mandanten-Slug", slugHint: "Verwenden Sie Kleinbuchstaben, Zahlen und einzelne Bindestriche.", description: "Beschreibung", descriptionHint: "Eine kurze Beschreibung dieses Mandanten und seines Angebots.", submissionEndpointsTitle: "Übermittlungsendpunkte", submissionEndpointsDescription: "Bereitstellungsweite Ziele für Produktfeedback und Ausführungsfehler. Ein leeres Feld deaktiviert den jeweiligen Übermittlungsweg.", feedbackSubmissionURL: "URL für Feedbackübermittlung", feedbackSubmissionURLHint: "Empfängt Feedback aus dieser Bereitstellung.", errorSubmissionURL: "URL für Fehlerübermittlung", errorSubmissionURLHint: "Empfängt Fehlerberichte aus dieser Bereitstellung.", submissionURLValidation: "Verwenden Sie zugangsdatenfreie HTTPS-URLs ohne Abfrage oder Fragment. Localhost-HTTP ist für die Entwicklung erlaubt.", saveHint: "Änderungen werden protokolliert und durch Revisionsprüfungen geschützt.", validation: "Geben Sie einen Namen und einen gültigen kleingeschriebenen Slug ein.", save: "Mandant speichern", identifiersTitle: "Mandantenkennungen", identifiersDescription: "Stabile Kennungen und Revisionen für Prüfung und Support.", tenantID: "Mandanten-ID", organisationID: "Organisations-ID", catalogRevision: "Katalogrevision", configurationRevision: "Konfigurationsrevision", saved: "Mandanteneinstellungen gespeichert.", saveFailed: "Mandanteneinstellungen konnten nicht gespeichert werden." },
  configurationSettings: { overviewDescription: "Effektive Startwerte, ihre Quelle und erforderliche Neustarts.", readOnly: "Schreibgeschützt", effectiveTitle: "Effektive Startkonfiguration", description: "Eingebaute Werte werden durch die zentrale Datei und anschließend durch Umgebungsvariablen überschrieben. Geheimnisse werden nie angezeigt.", unavailable: "Die effektive Konfiguration ist in der Beispieldatenansicht nicht verfügbar.", loading: "Effektive Konfiguration wird geladen…", loadError: "Die effektive Konfiguration konnte nicht geladen werden.", fileLoaded: "Zentrale Konfigurationsdatei:", noFile: "Keine zentrale Konfigurationsdatei ist geladen.", environmentAndDefaults: "Umgebungsvariablen und eingebaute Werte sind aktiv.", restartNotice: "Die Konfiguration wird beim Prozessstart gelesen. Änderungen erfordern einen Neustart des Dienstes oder Crawlers.", key: "Schlüssel", effectiveValue: "Effektiver Wert", source: "Quelle", configuredRedacted: "Konfiguriert · verborgen", notConfigured: "Nicht konfiguriert", sourceBuiltIn: "Eingebaut", sourceFile: "Zentrale Datei", sourceEnvironment: "Umgebung" },
  managedConfiguration: { title: "Durch die zentrale Konfiguration verwaltet.", description: "Konfigurierte Felder sind hier schreibgeschützt und werden nach einem Neustart des Dienstes aktualisiert.", fieldHint: "Dieser Wert wird durch die zentrale Konfiguration verwaltet." },
  workspace: { fixturePreview: "Testdatenvorschau", fixtureDescription: "Beispieldaten nur für die Entwicklung.", loadingData: "Bereitstellungsdaten werden geladen", partialLoadFailure: "Einige Daten konnten nicht geladen werden", loadingToolDraft: "HTTP-Werkzeugentwurf wird geladen", toolDraftUnavailable: "HTTP-Werkzeugentwurf nicht verfügbar", owningApiUnavailable: "Zugehörige API nicht verfügbar", returnToTools: "Zurück zu Werkzeugen" },
  title: { main: "DokoSoko" },
  ...deUI,
  settings: { ...deUI.settings, title: "Einstellungen", allAPIs: "Alle APIs", noRecipesYet: "Noch keine Rezepte" },
};
