import { esUI } from "./ui/es";

export const es = {
  metadata: { title: "DokoSoko — Panel de control de entrega para agentes", description: "Configura conocimiento de API de confianza, herramientas, identidad de clientes y acceso MCP desde una sola consola." },
  languages: { label: "Idioma", select: "Seleccionar idioma", en: "English", es: "Español", fr: "Français", de: "Deutsch", ja: "日本語", uk: "Українська", ptBR: "Português (Brasil)" },
  theme: { darkMode: "Modo oscuro", switchToLight: "Cambiar al modo claro", switchToDark: "Cambiar al modo oscuro" },
  navigation: { main: "Navegación principal", sectionLabel: "Secciones de {{name}}", consoleSection: "Sección de la consola", deployment: "Implementación", apis: "API", docs: "Documentación", sdksAndPackages: "SDK y paquetes", identity: "Identidad", tools: "Herramientas", recipes: "Recetas", agentAccess: "Acceso de agentes", supportOutbox: "Bandeja de soporte", settings: "Configuración", sources: "Fuentes", allFiles: "Todos los archivos", collections: "Colecciones", apiContracts: "Contratos de API", queryLab: "Laboratorio de consultas", packages: "Paquetes", customerSignIn: "Inicio de sesión de clientes", catalog: "Catálogo", connections: "Conexiones", mcpPreview: "Vista previa de MCP" },
  account: { defaultName: "Yuriy", defaultAdminName: "Administrador Yuriy", rootAdministrator: "Administrador raíz", platformAdmin: "Administrador de la plataforma", signOut: "Cerrar sesión" },
  common: { skipToContent: "Ir al contenido", reload: "Recargar", retry: "Reintentar", close: "Cerrar", save: "Guardar", cancel: "Cancelar", loading: "Cargando…", saving: "Guardando…", creating: "Creando…", verifying: "Verificando…", copied: "Copiado", notAvailable: "No disponible", notSpecified: "No especificado", none: "Ninguno", all: "Todos", public: "Público", private: "Privado", global: "Global", combined: "Combinado", contract: "Contrato", execution: "Ejecución", authorization: "Autorización", tests: "Pruebas", usage: "Uso", files: "Archivos", symbols: "Símbolos", samples: "Ejemplos", map: "Mapa", diagnostics: "Diagnósticos", usedByApis: "Usado por API", members: "Miembros", manifest: "Manifiesto", review: "Revisión", operations: "Operaciones", schemas: "Esquemas", examples: "Ejemplos", normalized: "Normalizado", aiAssist: "Asistencia de IA", import: "Importar", manual: "Manual", detail: "Detalle", sections: "Secciones", runStatus: "Estado de ejecución", active: "Activo", archived: "Archivado" },
  enumLabels: { active: "Activo", archived: "Archivado", attached: "Asociado", cancelled: "Cancelado", critical: "Crítico", deprecated: "Obsoleto", detached: "Desasociado", draft: "Borrador", excluded: "Excluido", failed: "Fallido", high: "Alto", included: "Incluido", low: "Bajo", medium: "Medio", needsReview: "Requiere revisión", partial: "Parcial", published: "Publicado", quarantined: "En cuarentena", queued: "En cola", ready: "Listo", retired: "Retirado", review: "En revisión", reviewReady: "Listo para revisión", running: "En ejecución", suspended: "Suspendido", valid: "Válido", validated: "Validado", yanked: "Retirado", metadataOnly: "Solo metadatos", resolvedSource: "Fuente resuelta", sourcePublication: "Publicación de fuente", document: "Documento", section: "Sección", unknown: "Desconocido ({{value}})" },
  format: { dateTime: "{{value, datetime}}", date: "{{value, datetime(year: numeric; month: short; day: numeric)}}", time: "{{value, datetime(hour: numeric; minute: 2-digit)}}", number: "{{value, number}}" },
  routes: { quickStart: "Inicio rápido", resources: "Recursos", keysAccess: "Claves y acceso", tools: "Herramientas", test: "Prueba", history: "Historial", documentation: "Documentación", apiContracts: "Contratos de API", sdks: "SDK", overview: "Resumen", databaseStorage: "Base de datos y almacenamiento", aiConfiguration: "Configuración de IA", rootAccess: "Acceso raíz" },
  workspace: { fixturePreview: "Vista previa de datos de prueba", fixtureDescription: "Datos de ejemplo solo para desarrollo.", loadingData: "Cargando datos de la implementación", partialLoadFailure: "No se pudieron cargar algunos datos", loadingToolDraft: "Cargando borrador de herramienta HTTP", toolDraftUnavailable: "El borrador de la herramienta HTTP no está disponible", owningApiUnavailable: "La API propietaria no está disponible", returnToTools: "Volver a herramientas" },
  title: { main: "DokoSoko" },
  ...esUI,
  settings: { ...esUI.settings, title: "Configuración", allAPIs: "Todas las API", noRecipesYet: "Aún no hay recetas" },
};
