import { esUI } from "./ui/es";

export const es = {
  metadata: { title: "DokoSoko — Panel de control de entrega para agentes", description: "Configura conocimiento de API de confianza, herramientas, identidad de clientes y acceso MCP desde una sola consola." },
  languages: { label: "Idioma", select: "Seleccionar idioma", en: "English", es: "Español", fr: "Français", de: "Deutsch", ja: "日本語", uk: "Українська", ptBR: "Português (Brasil)" },
  theme: { darkMode: "Modo oscuro", switchToLight: "Cambiar al modo claro", switchToDark: "Cambiar al modo oscuro", label: "Tema", select: "Seleccionar tema", light: "Claro", dark: "Oscuro", system: "Sistema", current: "Tema: {{theme}}", controlHint: "Tema {{theme}}. Haz clic para cambiar; mantén pulsado para ver las opciones." },
  navigation: { main: "Navegación principal", sectionLabel: "Secciones de {{name}}", consoleSection: "Sección de la consola", deployment: "Implementación", apis: "API", docs: "Documentación", sdksAndPackages: "SDK y paquetes", identity: "Identidad", tools: "Herramientas", recipes: "Recetas", agentAccess: "Acceso de agentes", supportOutbox: "Bandeja de soporte", settings: "Configuración", sources: "Fuentes", documents: "Documentos", apiContracts: "Contratos de API", queryLab: "Laboratorio de consultas", packages: "Paquetes", customerSignIn: "Inicio de sesión de clientes", customerAccounts: "Cuentas de clientes", catalog: "Catálogo", connections: "Conexiones", mcpPreview: "Vista previa de MCP" },
  account: { defaultName: "Yuriy", defaultAdminName: "Administrador Yuriy", rootAdministrator: "Administrador raíz", platformAdmin: "Administrador de la plataforma", signOut: "Cerrar sesión" },
  common: { skipToContent: "Ir al contenido", reload: "Recargar", retry: "Reintentar", close: "Cerrar", save: "Guardar", cancel: "Cancelar", loading: "Cargando…", saving: "Guardando…", creating: "Creando…", verifying: "Verificando…", copied: "Copiado", notAvailable: "No disponible", notSpecified: "No especificado", none: "Ninguno", all: "Todos", public: "Público", private: "Privado", global: "Global", combined: "Combinado", contract: "Contrato", execution: "Ejecución", authorization: "Autorización", tests: "Pruebas", usage: "Uso", files: "Archivos", symbols: "Símbolos", samples: "Ejemplos", map: "Mapa", diagnostics: "Diagnósticos", usedByApis: "Usado por API", members: "Miembros", manifest: "Manifiesto", review: "Revisión", operations: "Operaciones", schemas: "Esquemas", examples: "Ejemplos", normalized: "Normalizado", aiAssist: "Asistencia de IA", import: "Importar", manual: "Manual", detail: "Detalle", sections: "Secciones", runStatus: "Estado de ejecución", active: "Activo", archived: "Archivado" },
  enumLabels: { active: "Activo", archived: "Archivado", attached: "Asociado", cancelled: "Cancelado", critical: "Crítico", deprecated: "Obsoleto", detached: "Desasociado", draft: "Borrador", excluded: "Excluido", failed: "Fallido", high: "Alto", included: "Incluido", low: "Bajo", medium: "Medio", needsReview: "Requiere revisión", partial: "Parcial", published: "Publicado", quarantined: "En cuarentena", queued: "En cola", ready: "Listo", retired: "Retirado", review: "En revisión", reviewReady: "Listo para revisión", running: "En ejecución", suspended: "Suspendido", valid: "Válido", validated: "Validado", yanked: "Retirado", metadataOnly: "Solo metadatos", resolvedSource: "Fuente resuelta", sourcePublication: "Publicación de fuente", document: "Documento", section: "Sección", unknown: "Desconocido ({{value}})" },
  format: { dateTime: "{{value, datetime}}", date: "{{value, datetime(year: numeric; month: short; day: numeric)}}", time: "{{value, datetime(hour: numeric; minute: 2-digit)}}", number: "{{value, number}}" },
  routes: { quickStart: "Inicio rápido", resources: "Recursos", keysAccess: "Claves y acceso", tools: "Herramientas", test: "Prueba", history: "Historial", documentation: "Documentación", apiContracts: "Contratos de API", sdks: "SDK", overview: "Resumen", tenantSettings: "Configuración del tenant", configuration: "Configuración", aiConfiguration: "Configuración de IA", rootAccess: "Acceso raíz" },
  tenantSettings: { overviewDescription: "Nombre, slug, descripción e identificadores del tenant.", profileTitle: "Perfil del tenant", profileDescription: "Actualiza los datos del tenant que aparecen en la consola y en la configuración de MCP.", name: "Nombre del tenant", nameHint: "Se muestra en el encabezado de la consola y en los botones de MCP para clientes.", slug: "Slug del tenant", slugHint: "Usa letras minúsculas, números y guiones simples.", description: "Descripción", descriptionHint: "Una breve descripción de este tenant y de lo que ofrece.", submissionEndpointsTitle: "Endpoints de envío", submissionEndpointsDescription: "Destinos de toda la implementación para comentarios del producto y errores de ejecución. Deja un campo vacío para desactivar esa entrega.", feedbackSubmissionURL: "URL de envío de comentarios", feedbackSubmissionURLHint: "Recibe comentarios enviados desde esta implementación.", errorSubmissionURL: "URL de envío de errores", errorSubmissionURLHint: "Recibe informes de errores enviados desde esta implementación.", submissionURLValidation: "Usa URLs HTTPS sin credenciales, consultas ni fragmentos. HTTP en localhost está permitido para desarrollo.", saveHint: "Los cambios se registran y se protegen mediante revisiones.", validation: "Introduce un nombre y un slug válido en minúsculas.", save: "Guardar tenant", identifiersTitle: "Identificadores del tenant", identifiersDescription: "Identificadores y revisiones estables para auditoría y soporte.", tenantID: "ID del tenant", organisationID: "ID de la organización", catalogRevision: "Revisión del catálogo", configurationRevision: "Revisión de la configuración", saved: "La configuración del tenant se guardó.", saveFailed: "No se pudo guardar la configuración del tenant." },
  configurationSettings: { overviewDescription: "Valores de inicio efectivos, su origen y el reinicio requerido.", readOnly: "Solo lectura", effectiveTitle: "Configuración de inicio efectiva", description: "Los valores integrados se reemplazan por el archivo central y después por las variables de entorno. Los secretos nunca se muestran.", unavailable: "La configuración efectiva no está disponible en la vista de datos de prueba.", loading: "Cargando configuración efectiva…", loadError: "No se pudo cargar la configuración efectiva.", fileLoaded: "Archivo de configuración central:", noFile: "No hay ningún archivo de configuración central cargado.", environmentAndDefaults: "Están activos las variables de entorno y los valores integrados.", restartNotice: "La configuración se lee al iniciar el proceso. Los cambios requieren reiniciar el servicio o el crawler.", key: "Clave", effectiveValue: "Valor efectivo", source: "Origen", configuredRedacted: "Configurado · oculto", notConfigured: "No configurado", sourceBuiltIn: "Integrado", sourceFile: "Archivo central", sourceEnvironment: "Entorno" },
  managedConfiguration: { title: "Gestionado por la configuración central.", description: "Los campos configurados son de solo lectura aquí y se actualizan al reiniciar el servicio.", fieldHint: "Este valor está gestionado por la configuración central." },
  workspace: { fixturePreview: "Vista previa de datos de prueba", fixtureDescription: "Datos de ejemplo solo para desarrollo.", loadingData: "Cargando datos de la implementación", partialLoadFailure: "No se pudieron cargar algunos datos", loadingToolDraft: "Cargando borrador de herramienta HTTP", toolDraftUnavailable: "El borrador de la herramienta HTTP no está disponible", owningApiUnavailable: "La API propietaria no está disponible", returnToTools: "Volver a herramientas" },
  title: { main: "DokoSoko" },
  ...esUI,
  settings: { ...esUI.settings, title: "Configuración", allAPIs: "Todas las API", noRecipesYet: "Aún no hay recetas" },
};
