import { frUI } from "./ui/fr";

export const fr = {
  metadata: { title: "DokoSoko — Plan de contrôle de livraison des agents", description: "Configurez les connaissances API fiables, les outils, l’identité client et l’accès MCP depuis une seule console." },
  languages: { label: "Langue", select: "Sélectionner la langue", en: "English", es: "Español", fr: "Français", de: "Deutsch", ja: "日本語", uk: "Українська", ptBR: "Português (Brasil)" },
  theme: { darkMode: "Mode sombre", switchToLight: "Passer au mode clair", switchToDark: "Passer au mode sombre" },
  navigation: { main: "Navigation principale", sectionLabel: "Sections de {{name}}", consoleSection: "Section de la console", deployment: "Déploiement", apis: "API", docs: "Documentation", sdksAndPackages: "SDK et paquets", identity: "Identité", tools: "Outils", recipes: "Recettes", agentAccess: "Accès des agents", supportOutbox: "Boîte d’envoi du support", settings: "Paramètres", sources: "Sources", allFiles: "Tous les fichiers", collections: "Collections", apiContracts: "Contrats API", queryLab: "Laboratoire de requêtes", packages: "Paquets", customerSignIn: "Connexion client", catalog: "Catalogue", connections: "Connexions", mcpPreview: "Aperçu MCP" },
  account: { defaultName: "Yuriy", defaultAdminName: "Administrateur Yuriy", rootAdministrator: "Administrateur racine", platformAdmin: "Administrateur de la plateforme", signOut: "Se déconnecter" },
  common: { skipToContent: "Aller au contenu", reload: "Recharger", retry: "Réessayer", close: "Fermer", save: "Enregistrer", cancel: "Annuler", loading: "Chargement…", saving: "Enregistrement…", creating: "Création…", verifying: "Vérification…", copied: "Copié", notAvailable: "Indisponible", notSpecified: "Non spécifié", none: "Aucun", all: "Tous", public: "Public", private: "Privé", global: "Global", combined: "Combiné", contract: "Contrat", execution: "Exécution", authorization: "Autorisation", tests: "Tests", usage: "Utilisation", files: "Fichiers", symbols: "Symboles", samples: "Exemples", map: "Carte", diagnostics: "Diagnostics", usedByApis: "Utilisé par les API", members: "Membres", manifest: "Manifeste", review: "Révision", operations: "Opérations", schemas: "Schémas", examples: "Exemples", normalized: "Normalisé", aiAssist: "Assistance IA", import: "Importer", manual: "Manuel", detail: "Détail", sections: "Sections", runStatus: "État de l’exécution", active: "Actif", archived: "Archivé" },
  enumLabels: { active: "Actif", archived: "Archivé", attached: "Attaché", cancelled: "Annulé", critical: "Critique", deprecated: "Obsolète", detached: "Détaché", draft: "Brouillon", excluded: "Exclu", failed: "Échec", high: "Élevé", included: "Inclus", low: "Faible", medium: "Moyen", needsReview: "À vérifier", partial: "Partiel", published: "Publié", quarantined: "En quarantaine", queued: "En attente", ready: "Prêt", retired: "Retiré", review: "En cours de révision", reviewReady: "Prêt pour révision", running: "En cours", suspended: "Suspendu", valid: "Valide", validated: "Validé", yanked: "Retiré", metadataOnly: "Métadonnées uniquement", resolvedSource: "Source résolue", sourcePublication: "Publication de source", document: "Document", section: "Section", unknown: "Inconnu ({{value}})" },
  format: { dateTime: "{{value, datetime}}", date: "{{value, datetime(year: numeric; month: short; day: numeric)}}", time: "{{value, datetime(hour: numeric; minute: 2-digit)}}", number: "{{value, number}}" },
  routes: { quickStart: "Démarrage rapide", resources: "Ressources", keysAccess: "Clés et accès", tools: "Outils", test: "Test", history: "Historique", documentation: "Documentation", apiContracts: "Contrats API", sdks: "SDK", overview: "Vue d’ensemble", databaseStorage: "Base de données et stockage", aiConfiguration: "Configuration de l’IA", rootAccess: "Accès racine" },
  workspace: { fixturePreview: "Aperçu des données de test", fixtureDescription: "Données d’exemple réservées au développement.", loadingData: "Chargement des données du déploiement", partialLoadFailure: "Certaines données n’ont pas pu être chargées", loadingToolDraft: "Chargement du brouillon de l’outil HTTP", toolDraftUnavailable: "Brouillon de l’outil HTTP indisponible", owningApiUnavailable: "API propriétaire indisponible", returnToTools: "Retour aux outils" },
  title: { main: "DokoSoko" },
  ...frUI,
  settings: { ...frUI.settings, title: "Paramètres", allAPIs: "Toutes les API", noRecipesYet: "Aucune recette pour le moment" },
};
