import { ptBRUI } from "./ui/pt-BR";

export const ptBR = {
  metadata: { title: "DokoSoko — Plano de controle de entrega de agentes", description: "Configure conhecimento confiável de APIs, ferramentas, identidade de clientes e acesso MCP em um único console." },
  languages: { label: "Idioma", select: "Selecionar idioma", en: "English", es: "Español", fr: "Français", de: "Deutsch", ja: "日本語", uk: "Українська", ptBR: "Português (Brasil)" },
  theme: { darkMode: "Modo escuro", switchToLight: "Mudar para o modo claro", switchToDark: "Mudar para o modo escuro" },
  navigation: { main: "Navegação principal", sectionLabel: "Seções de {{name}}", consoleSection: "Seção do console", deployment: "Implantação", apis: "APIs", docs: "Documentação", sdksAndPackages: "SDKs e pacotes", identity: "Identidade", tools: "Ferramentas", recipes: "Receitas", agentAccess: "Acesso de agentes", supportOutbox: "Caixa de saída do suporte", settings: "Configurações", sources: "Fontes", allFiles: "Todos os arquivos", collections: "Coleções", apiContracts: "Contratos de API", queryLab: "Laboratório de consultas", packages: "Pacotes", customerSignIn: "Login do cliente", catalog: "Catálogo", connections: "Conexões", mcpPreview: "Prévia do MCP" },
  account: { defaultName: "Yuriy", defaultAdminName: "Administrador Yuriy", rootAdministrator: "Administrador raiz", platformAdmin: "Administrador da plataforma", signOut: "Sair" },
  common: { skipToContent: "Ir para o conteúdo", reload: "Recarregar", retry: "Tentar novamente", close: "Fechar", save: "Salvar", cancel: "Cancelar", loading: "Carregando…", saving: "Salvando…", creating: "Criando…", verifying: "Verificando…", copied: "Copiado", notAvailable: "Indisponível", notSpecified: "Não especificado", none: "Nenhum", all: "Todos", public: "Público", private: "Privado", global: "Global", combined: "Combinado", contract: "Contrato", execution: "Execução", authorization: "Autorização", tests: "Testes", usage: "Uso", files: "Arquivos", symbols: "Símbolos", samples: "Exemplos", map: "Mapa", diagnostics: "Diagnósticos", usedByApis: "Usado por APIs", members: "Membros", manifest: "Manifesto", review: "Revisão", operations: "Operações", schemas: "Esquemas", examples: "Exemplos", normalized: "Normalizado", aiAssist: "Assistência de IA", import: "Importar", manual: "Manual", detail: "Detalhes", sections: "Seções", runStatus: "Status da execução", active: "Ativo", archived: "Arquivado" },
  enumLabels: { active: "Ativo", archived: "Arquivado", attached: "Vinculado", cancelled: "Cancelado", critical: "Crítico", deprecated: "Obsoleto", detached: "Desvinculado", draft: "Rascunho", excluded: "Excluído", failed: "Falhou", high: "Alto", included: "Incluído", low: "Baixo", medium: "Médio", needsReview: "Requer revisão", partial: "Parcial", published: "Publicado", quarantined: "Em quarentena", queued: "Na fila", ready: "Pronto", retired: "Desativado", review: "Em revisão", reviewReady: "Pronto para revisão", running: "Em execução", suspended: "Suspenso", valid: "Válido", validated: "Validado", yanked: "Retirado", metadataOnly: "Somente metadados", resolvedSource: "Fonte resolvida", sourcePublication: "Publicação da fonte", document: "Documento", section: "Seção", unknown: "Desconhecido ({{value}})" },
  format: { dateTime: "{{value, datetime}}", date: "{{value, datetime(year: numeric; month: short; day: numeric)}}", time: "{{value, datetime(hour: numeric; minute: 2-digit)}}", number: "{{value, number}}" },
  routes: { quickStart: "Início rápido", resources: "Recursos", keysAccess: "Chaves e acesso", tools: "Ferramentas", test: "Teste", history: "Histórico", documentation: "Documentação", apiContracts: "Contratos de API", sdks: "SDKs", overview: "Visão geral", databaseStorage: "Banco de dados e armazenamento", aiConfiguration: "Configuração de IA", rootAccess: "Acesso raiz" },
  workspace: { fixturePreview: "Prévia de dados de teste", fixtureDescription: "Dados de exemplo somente para desenvolvimento.", loadingData: "Carregando dados da implantação", partialLoadFailure: "Alguns dados não puderam ser carregados", loadingToolDraft: "Carregando rascunho da ferramenta HTTP", toolDraftUnavailable: "Rascunho da ferramenta HTTP indisponível", owningApiUnavailable: "API proprietária indisponível", returnToTools: "Voltar para ferramentas" },
  title: { main: "DokoSoko" },
  ...ptBRUI,
  settings: { ...ptBRUI.settings, title: "Configurações", allAPIs: "Todas as APIs", noRecipesYet: "Nenhuma receita ainda" },
};
