import { ptBRUI } from "./ui/pt-BR";

export const ptBR = {
  metadata: { title: "DokoSoko — Plano de controle de entrega de agentes", description: "Configure conhecimento confiável de APIs, ferramentas, identidade de clientes e acesso MCP em um único console." },
  languages: { label: "Idioma", select: "Selecionar idioma", en: "English", es: "Español", fr: "Français", de: "Deutsch", ja: "日本語", uk: "Українська", ptBR: "Português (Brasil)" },
  theme: { darkMode: "Modo escuro", switchToLight: "Mudar para o modo claro", switchToDark: "Mudar para o modo escuro", label: "Tema", select: "Selecionar tema", light: "Claro", dark: "Escuro", system: "Sistema", current: "Tema: {{theme}}", controlHint: "Tema {{theme}}. Clique para alternar; mantenha pressionado para ver as opções." },
  navigation: { main: "Navegação principal", sectionLabel: "Seções de {{name}}", consoleSection: "Seção do console", deployment: "Implantação", apis: "APIs", docs: "Documentação", sdksAndPackages: "SDKs e pacotes", identity: "Identidade", tools: "Ferramentas", recipes: "Receitas", agentAccess: "Acesso de agentes", supportOutbox: "Caixa de saída do suporte", settings: "Configurações", sources: "Fontes", documents: "Documentos", apiContracts: "Contratos de API", queryLab: "Laboratório de consultas", packages: "Pacotes", customerSignIn: "Login do cliente", customerAccounts: "Contas de clientes", catalog: "Catálogo", connections: "Conexões", mcpPreview: "Prévia do MCP" },
  account: { defaultName: "Yuriy", defaultAdminName: "Administrador Yuriy", rootAdministrator: "Administrador raiz", platformAdmin: "Administrador da plataforma", signOut: "Sair" },
  common: { skipToContent: "Ir para o conteúdo", reload: "Recarregar", retry: "Tentar novamente", close: "Fechar", save: "Salvar", cancel: "Cancelar", loading: "Carregando…", saving: "Salvando…", creating: "Criando…", verifying: "Verificando…", copied: "Copiado", notAvailable: "Indisponível", notSpecified: "Não especificado", none: "Nenhum", all: "Todos", public: "Público", private: "Privado", global: "Global", combined: "Combinado", contract: "Contrato", execution: "Execução", authorization: "Autorização", tests: "Testes", usage: "Uso", files: "Arquivos", symbols: "Símbolos", samples: "Exemplos", map: "Mapa", diagnostics: "Diagnósticos", usedByApis: "Usado por APIs", members: "Membros", manifest: "Manifesto", review: "Revisão", operations: "Operações", schemas: "Esquemas", examples: "Exemplos", normalized: "Normalizado", aiAssist: "Assistência de IA", import: "Importar", manual: "Manual", detail: "Detalhes", sections: "Seções", runStatus: "Status da execução", active: "Ativo", archived: "Arquivado" },
  enumLabels: { active: "Ativo", archived: "Arquivado", attached: "Vinculado", cancelled: "Cancelado", critical: "Crítico", deprecated: "Obsoleto", detached: "Desvinculado", draft: "Rascunho", excluded: "Excluído", failed: "Falhou", high: "Alto", included: "Incluído", low: "Baixo", medium: "Médio", needsReview: "Requer revisão", partial: "Parcial", published: "Publicado", quarantined: "Em quarentena", queued: "Na fila", ready: "Pronto", retired: "Desativado", review: "Em revisão", reviewReady: "Pronto para revisão", running: "Em execução", suspended: "Suspenso", valid: "Válido", validated: "Validado", yanked: "Retirado", metadataOnly: "Somente metadados", resolvedSource: "Fonte resolvida", sourcePublication: "Publicação da fonte", document: "Documento", section: "Seção", unknown: "Desconhecido ({{value}})" },
  format: { dateTime: "{{value, datetime}}", date: "{{value, datetime(year: numeric; month: short; day: numeric)}}", time: "{{value, datetime(hour: numeric; minute: 2-digit)}}", number: "{{value, number}}" },
  routes: { quickStart: "Início rápido", resources: "Recursos", keysAccess: "Chaves e acesso", tools: "Ferramentas", test: "Teste", history: "Histórico", documentation: "Documentação", apiContracts: "Contratos de API", sdks: "SDKs", overview: "Visão geral", tenantSettings: "Configurações do tenant", configuration: "Configuração", aiConfiguration: "Configuração de IA", rootAccess: "Acesso raiz" },
  tenantSettings: { overviewDescription: "Nome, slug, descrição e identificadores do tenant.", profileTitle: "Perfil do tenant", profileDescription: "Atualize os dados do tenant exibidos no console e na configuração do MCP.", name: "Nome do tenant", nameHint: "Exibido no cabeçalho do console e nos botões MCP voltados aos clientes.", slug: "Slug do tenant", slugHint: "Use letras minúsculas, números e hífens simples.", description: "Descrição", descriptionHint: "Uma breve descrição deste tenant e do que ele oferece.", submissionEndpointsTitle: "Endpoints de envio", submissionEndpointsDescription: "Destinos de toda a implantação para feedback do produto e erros de execução. Deixe um campo vazio para desativar essa entrega.", feedbackSubmissionURL: "URL de envio de feedback", feedbackSubmissionURLHint: "Recebe feedback enviado desta implantação.", errorSubmissionURL: "URL de envio de erros", errorSubmissionURLHint: "Recebe relatórios de erro enviados desta implantação.", submissionURLValidation: "Use URLs HTTPS sem credenciais, consulta ou fragmento. HTTP em localhost é permitido para desenvolvimento.", saveHint: "As alterações são registradas para auditoria e protegidas por revisões.", validation: "Informe um nome e um slug válido em minúsculas.", save: "Salvar tenant", identifiersTitle: "Identificadores do tenant", identifiersDescription: "Identificadores e revisões estáveis para auditoria e suporte.", tenantID: "ID do tenant", organisationID: "ID da organização", catalogRevision: "Revisão do catálogo", configurationRevision: "Revisão da configuração", saved: "Configurações do tenant salvas.", saveFailed: "Não foi possível salvar as configurações do tenant." },
  configurationSettings: { overviewDescription: "Valores efetivos de inicialização, sua origem e o reinício necessário.", readOnly: "Somente leitura", effectiveTitle: "Configuração efetiva de inicialização", description: "Os valores internos são substituídos pelo arquivo central e depois pelas variáveis de ambiente. Segredos nunca são exibidos.", unavailable: "A configuração efetiva não está disponível na visualização de dados de exemplo.", loading: "Carregando configuração efetiva…", loadError: "Não foi possível carregar a configuração efetiva.", fileLoaded: "Arquivo de configuração central:", noFile: "Nenhum arquivo de configuração central está carregado.", environmentAndDefaults: "Variáveis de ambiente e valores internos estão ativos.", restartNotice: "A configuração é lida na inicialização do processo. Alterações exigem reiniciar o serviço ou crawler.", key: "Chave", effectiveValue: "Valor efetivo", source: "Origem", configuredRedacted: "Configurado · oculto", notConfigured: "Não configurado", sourceBuiltIn: "Interno", sourceFile: "Arquivo central", sourceEnvironment: "Ambiente" },
  managedConfiguration: { title: "Gerenciado pela configuração central.", description: "Os campos configurados são somente leitura aqui e são atualizados após reiniciar o serviço.", fieldHint: "Este valor é gerenciado pela configuração central." },
  workspace: { fixturePreview: "Prévia de dados de teste", fixtureDescription: "Dados de exemplo somente para desenvolvimento.", loadingData: "Carregando dados da implantação", partialLoadFailure: "Alguns dados não puderam ser carregados", loadingToolDraft: "Carregando rascunho da ferramenta HTTP", toolDraftUnavailable: "Rascunho da ferramenta HTTP indisponível", owningApiUnavailable: "API proprietária indisponível", returnToTools: "Voltar para ferramentas" },
  title: { main: "DokoSoko" },
  ...ptBRUI,
  settings: { ...ptBRUI.settings, title: "Configurações", allAPIs: "Todas as APIs", noRecipesYet: "Nenhuma receita ainda" },
};
