import { ukUI } from "./ui/uk";

export const uk = {
  metadata: { title: "DokoSoko — Панель керування доставкою агентів", description: "Налаштовуйте надійні знання про API, інструменти, ідентифікацію клієнтів і доступ MCP в одній консолі." },
  languages: { label: "Мова", select: "Вибрати мову", en: "English", es: "Español", fr: "Français", de: "Deutsch", ja: "日本語", uk: "Українська", ptBR: "Português (Brasil)" },
  theme: { darkMode: "Темний режим", switchToLight: "Перейти до світлого режиму", switchToDark: "Перейти до темного режиму", label: "Тема", select: "Вибрати тему", light: "Світла", dark: "Темна", system: "Системна", current: "Тема: {{theme}}", controlHint: "Тема: {{theme}}. Натисніть, щоб змінити; утримуйте, щоб відкрити варіанти." },
  navigation: { main: "Головна навігація", sectionLabel: "Розділи: {{name}}", consoleSection: "Розділ консолі", deployment: "Розгортання", apis: "API", docs: "Документація", sdksAndPackages: "SDK і пакети", identity: "Ідентифікація", tools: "Інструменти", recipes: "Рецепти", agentAccess: "Доступ агентів", supportOutbox: "Вихідні звернення", settings: "Налаштування", sources: "Джерела", documents: "Документи", apiContracts: "Контракти API", queryLab: "Лабораторія запитів", packages: "Пакети", customerSignIn: "Вхід клієнта", customerAccounts: "Облікові записи клієнтів", catalog: "Каталог", connections: "Підключення", mcpPreview: "Попередній перегляд MCP" },
  account: { defaultName: "Yuriy", defaultAdminName: "Адміністратор Yuriy", rootAdministrator: "Кореневий адміністратор", platformAdmin: "Адміністратор платформи", signOut: "Вийти" },
  common: { skipToContent: "Перейти до вмісту", reload: "Перезавантажити", retry: "Спробувати знову", close: "Закрити", save: "Зберегти", cancel: "Скасувати", loading: "Завантаження…", saving: "Збереження…", creating: "Створення…", verifying: "Перевірка…", copied: "Скопійовано", notAvailable: "Недоступно", notSpecified: "Не вказано", none: "Немає", all: "Усі", public: "Публічний", private: "Приватний", global: "Глобальний", combined: "Об’єднаний", contract: "Контракт", execution: "Виконання", authorization: "Авторизація", tests: "Тести", usage: "Використання", files: "Файли", symbols: "Символи", samples: "Зразки", map: "Мапа", diagnostics: "Діагностика", usedByApis: "Використовується API", members: "Учасники", manifest: "Маніфест", review: "Перевірка", operations: "Операції", schemas: "Схеми", examples: "Приклади", normalized: "Нормалізовано", aiAssist: "Допомога ШІ", import: "Імпорт", manual: "Вручну", detail: "Деталі", sections: "Розділи", runStatus: "Стан виконання", active: "Активний", archived: "Архівний" },
  enumLabels: { active: "Активний", archived: "Архівний", attached: "Прикріплено", cancelled: "Скасовано", critical: "Критичний", deprecated: "Застарілий", detached: "Від’єднано", draft: "Чернетка", excluded: "Виключено", failed: "Помилка", high: "Високий", included: "Включено", low: "Низький", medium: "Середній", needsReview: "Потрібна перевірка", partial: "Частково", published: "Опубліковано", quarantined: "На карантині", queued: "У черзі", ready: "Готово", retired: "Виведено з експлуатації", review: "На перевірці", reviewReady: "Готово до перевірки", running: "Виконується", suspended: "Призупинено", valid: "Дійсний", validated: "Перевірено", yanked: "Відкликано", metadataOnly: "Лише метадані", resolvedSource: "Визначене джерело", sourcePublication: "Публікація джерела", document: "Документ", section: "Розділ", unknown: "Невідомо ({{value}})" },
  format: { dateTime: "{{value, datetime}}", date: "{{value, datetime(year: numeric; month: short; day: numeric)}}", time: "{{value, datetime(hour: numeric; minute: 2-digit)}}", number: "{{value, number}}" },
  routes: { quickStart: "Швидкий старт", resources: "Ресурси", keysAccess: "Ключі та доступ", tools: "Інструменти", test: "Тест", history: "Історія", documentation: "Документація", apiContracts: "Контракти API", sdks: "SDK", overview: "Огляд", tenantSettings: "Налаштування тенанта", aiConfiguration: "Налаштування ШІ", rootAccess: "Кореневий доступ" },
  tenantSettings: { overviewDescription: "Назва, слаг, опис та ідентифікатори тенанта.", profileTitle: "Профіль тенанта", profileDescription: "Оновіть дані тенанта, які відображаються в консолі та налаштуванні MCP.", name: "Назва тенанта", nameHint: "Відображається в заголовку консолі та клієнтських кнопках MCP.", slug: "Слаг тенанта", slugHint: "Використовуйте малі літери, цифри та одиночні дефіси.", description: "Опис", descriptionHint: "Короткий опис цього тенанта та його призначення.", submissionEndpointsTitle: "Кінцеві точки надсилання", submissionEndpointsDescription: "Спільні для розгортання адреси для відгуків про продукт і помилок виконання. Залиште поле порожнім, щоб вимкнути відповідне надсилання.", feedbackSubmissionURL: "URL надсилання відгуків", feedbackSubmissionURLHint: "Отримує відгуки, надіслані з цього розгортання.", errorSubmissionURL: "URL надсилання помилок", errorSubmissionURLHint: "Отримує звіти про помилки з цього розгортання.", submissionURLValidation: "Використовуйте HTTPS URL без облікових даних, запитів і фрагментів. HTTP для localhost дозволено під час розробки.", saveHint: "Зміни записуються в журнал аудиту та захищені перевіркою ревізії.", validation: "Введіть назву та дійсний слаг малими літерами.", save: "Зберегти тенант", identifiersTitle: "Ідентифікатори тенанта", identifiersDescription: "Стабільні ідентифікатори та ревізії для аудиту й підтримки.", tenantID: "ID тенанта", organisationID: "ID організації", catalogRevision: "Ревізія каталогу", configurationRevision: "Ревізія конфігурації", saved: "Налаштування тенанта збережено.", saveFailed: "Не вдалося зберегти налаштування тенанта." },
  workspace: { fixturePreview: "Попередній перегляд тестових даних", fixtureDescription: "Зразки даних лише для розробки.", loadingData: "Завантаження даних розгортання", partialLoadFailure: "Деякі дані не вдалося завантажити", loadingToolDraft: "Завантаження чернетки HTTP-інструмента", toolDraftUnavailable: "Чернетка HTTP-інструмента недоступна", owningApiUnavailable: "API-власник недоступний", returnToTools: "Повернутися до інструментів" },
  title: { main: "DokoSoko" },
  ...ukUI,
  settings: { ...ukUI.settings, title: "Налаштування", allAPIs: "Усі API", noRecipesYet: "Рецептів ще немає" },
};
