"use client";

import type { APIRecipe, APIRecipeRevision } from "../../../lib/api";
import { Badge, Button, Dialog } from "../../core/control";
import type { RecipeApprovalReview } from "./recipe-approval-review";

function findingColor(level: APIRecipeRevision["validation"][number]["level"]): "blue" | "amber" | "red" {
  if (level === "error") return "red";
  if (level === "warning") return "amber";
  return "blue";
}

function generatedByLabel(value: APIRecipeRevision["generated_by"]): string {
  if (value === "ai") return "AI";
  return value.charAt(0).toUpperCase() + value.slice(1);
}

export function RecipeApprovalDialog({ review, busy, onClose, onApprove }: {
  review: RecipeApprovalReview | null;
  busy: boolean;
  onClose: () => void;
  onApprove: (recipe: APIRecipe) => void | Promise<void>;
}) {
  if (!review) return null;

  const { recipe, revision, currentRevisionID, integration } = review;
  const integrationID = revision.spec_version === 2 ? revision.spec.integration_id : recipe.integration_id;
  const promptVersion = revision.prompt_version || (revision.generated_by === "ai" ? "Not recorded" : "Not applicable");
  const promptHash = revision.prompt_hash || (revision.generated_by === "ai" ? "Not recorded" : "Not applicable");

  async function approveReviewedRevision() {
    await onApprove(recipe);
    onClose();
  }

  return <Dialog
    open
    onClose={(open) => { if (!open && !busy) onClose(); }}
    title={`Approve ${recipe.title} · revision ${revision.revision}`}
    description="Review the exact immutable revision below. Approval applies only to the displayed current revision ID; a concurrent change is rejected by the server."
    actions={<><Button outline disabled={busy} onClick={onClose}>Cancel</Button><Button disabled={busy} onClick={() => void approveReviewedRevision()}>{busy ? "Approving…" : `Approve revision ${revision.revision}`}</Button></>}
  >
    <div className="recipe-approval-review">
      <section aria-labelledby="recipe-approval-binding-heading">
        <h3 id="recipe-approval-binding-heading">Revision and integration binding</h3>
        <dl className="entity-detail-grid recipe-approval-metadata">
          <div><dt>Revision number</dt><dd>{revision.revision}</dd></div>
          <div><dt>Current revision ID</dt><dd><code>{currentRevisionID}</code></dd></div>
          <div><dt>Integration</dt><dd>{integration?.display_name ?? "Unavailable"}</dd></div>
          <div><dt>Integration ID</dt><dd><code>{integrationID || "Not recorded"}</code></dd></div>
          <div><dt>Integration revision ID</dt><dd><code>{revision.integration_revision_id || "Not recorded"}</code></dd></div>
          <div><dt>Integration manifest hash</dt><dd><code>{revision.integration_manifest_hash || "Not recorded"}</code></dd></div>
        </dl>
      </section>

      <section aria-labelledby="recipe-approval-provenance-heading">
        <h3 id="recipe-approval-provenance-heading">Generation provenance</h3>
        <dl className="entity-detail-grid recipe-approval-metadata">
          <div><dt>Generated by</dt><dd>{generatedByLabel(revision.generated_by)}</dd></div>
          <div><dt>Model</dt><dd>{revision.model || "Not applicable"}</dd></div>
          <div><dt>Prompt version</dt><dd>{promptVersion}</dd></div>
          <div><dt>Prompt hash</dt><dd><code>{promptHash}</code></dd></div>
          <div><dt>Created by</dt><dd>{revision.created_by}</dd></div>
          <div><dt>Created</dt><dd>{new Date(revision.created_at).toLocaleString()}</dd></div>
        </dl>
      </section>

      <section aria-labelledby="recipe-approval-validation-heading">
        <h3 id="recipe-approval-validation-heading">Validation findings</h3>
        {revision.validation.length > 0 ? <ul className="recipe-approval-list">
          {revision.validation.map((finding, index) => <li key={`${finding.level}:${finding.code}:${index}`}>
            <Badge color={findingColor(finding.level)}>{finding.level}</Badge>
            <span><strong>{finding.code}</strong><small>{finding.message}</small></span>
          </li>)}
        </ul> : <p className="recipe-approval-empty">No validation findings were recorded for this revision.</p>}
      </section>

      <section aria-labelledby="recipe-approval-references-heading">
        <h3 id="recipe-approval-references-heading">References</h3>
        {revision.references && revision.references.length > 0 ? <ul className="recipe-approval-list recipe-approval-references">
          {revision.references.map((reference, index) => <li key={`${reference.kind}:${reference.resource_id ?? reference.url}:${index}`}>
            <Badge>{reference.kind}</Badge>
            <span>
              <strong><a href={reference.url} target="_blank" rel="noreferrer">{reference.label}</a></strong>
              <small>{reference.resource_id ? `${reference.resource_id} · ` : ""}{reference.url}{reference.anchor ? ` · ${reference.anchor}` : ""}</small>
            </span>
          </li>)}
        </ul> : <p className="recipe-approval-empty">No references were selected for this revision.</p>}
      </section>

      <section aria-labelledby="recipe-approval-markdown-heading">
        <h3 id="recipe-approval-markdown-heading">Canonical Markdown</h3>
        <pre className="recipe-approval-markdown" role="region" aria-label={`Canonical Markdown for revision ${revision.revision}`}><code>{revision.markdown || "No canonical Markdown was recorded."}</code></pre>
      </section>
    </div>
  </Dialog>;
}
