package store

import (
	"context"
	"errors"
	"time"

	"github.com/dokosoko/dokosoko-service/internal/identity"
	"github.com/dokosoko/dokosoko-service/internal/model"
)

var (
	ErrNotFound = errors.New("not found")
	ErrConflict = errors.New("revision conflict")
)

type Store interface {
	Organisations(context.Context) ([]model.Organisation, error)
	CreateOrganisation(context.Context, model.Organisation) (model.Organisation, error)
	Deployment(context.Context) (model.Deployment, error)
	CreateDeployment(context.Context, model.Deployment) (model.Deployment, error)
	UpdateDeployment(context.Context, model.Deployment, int64) (model.Deployment, error)
	Integrations(context.Context, string) ([]model.Integration, error)
	Integration(context.Context, string, string) (model.Integration, error)
	CreateIntegration(context.Context, model.Integration) (model.Integration, error)
	UpdateIntegration(context.Context, model.Integration, int64) (model.Integration, error)
	IntegrationRevisions(context.Context, string) ([]model.IntegrationRevision, error)
	CreateIntegrationRevision(context.Context, model.IntegrationRevision) (model.IntegrationRevision, error)
	ResourceSets(context.Context, string, string) ([]model.ResourceSet, error)
	ResourceSet(context.Context, string, string) (model.ResourceSet, error)
	CreateResourceSet(context.Context, model.ResourceSet, model.ResourceSetRevision) (model.ResourceSet, error)
	UpdateResourceSet(context.Context, model.ResourceSet, model.ResourceSetRevision, int64) (model.ResourceSet, error)
	ResourceSetRevisions(context.Context, string) ([]model.ResourceSetRevision, error)
	IntegrationResourceLinks(context.Context, string) ([]model.IntegrationResourceLink, error)
	SaveIntegrationResourceLink(context.Context, model.IntegrationResourceLink) (model.IntegrationResourceLink, error)
	DeleteIntegrationResourceLink(context.Context, string, string) error
	PackageArtifacts(context.Context, string) ([]model.PackageArtifact, error)
	PackageArtifact(context.Context, string, string) (model.PackageArtifact, error)
	CreatePackageArtifact(context.Context, model.PackageArtifact) (model.PackageArtifact, error)
	UpdatePackageArtifact(context.Context, model.PackageArtifact, int64) (model.PackageArtifact, error)
	PackageReleases(context.Context, string) ([]model.PackageRelease, error)
	PackageRelease(context.Context, string, string) (model.PackageRelease, error)
	CreatePackageRelease(context.Context, string, model.PackageRelease, int64) (model.PackageArtifact, model.PackageRelease, error)
	IntegrationPackageBindings(context.Context, string) ([]model.IntegrationPackageBinding, error)
	SaveIntegrationPackageBinding(context.Context, model.IntegrationPackageBinding) (model.IntegrationPackageBinding, error)
	DeleteIntegrationPackageBinding(context.Context, string, string) error
	GrantDefinitions(context.Context, string) ([]model.GrantDefinition, error)
	GrantDefinition(context.Context, string, string) (model.GrantDefinition, error)
	SaveGrantDefinition(context.Context, model.GrantDefinition, int64) (model.GrantDefinition, error)
	AuthorizationPoints(context.Context, string) ([]model.AuthorizationPoint, error)
	AuthorizationPoint(context.Context, string, string) (model.AuthorizationPoint, error)
	SaveAuthorizationPoint(context.Context, model.AuthorizationPoint, int64) (model.AuthorizationPoint, error)
	IntegrationToolBindings(context.Context, string) ([]model.IntegrationToolBinding, error)
	SaveIntegrationToolBindings(context.Context, string, []model.IntegrationToolBinding) ([]model.IntegrationToolBinding, error)
	AccessDefinitions(context.Context, string) ([]model.AccessDefinition, error)
	AccessDefinition(context.Context, string, string) (model.AccessDefinition, error)
	CreateAccessDefinition(context.Context, model.AccessDefinition) (model.AccessDefinition, error)
	AccessConnections(context.Context, string) ([]model.AccessConnection, error)
	AccessConnection(context.Context, string, string) (model.AccessConnection, error)
	CreateAccessConnection(context.Context, model.AccessConnection) (model.AccessConnection, error)
	SetIntegrationAccessConnections(context.Context, string, string, []string, string) error
	AccessInstances(context.Context, string, string) ([]model.AccessInstance, error)
	AccessInstance(context.Context, string, string) (model.AccessInstance, error)
	CreateAccessInstance(context.Context, model.AccessInstance) (model.AccessInstance, error)
	AccessCredentials(context.Context, string, string, string) ([]model.AccessCredential, error)
	AccessCredential(context.Context, string, string) (model.AccessCredential, error)
	CreateAccessCredential(context.Context, model.AccessCredential) (model.AccessCredential, error)
	RevokeAccessCredential(context.Context, string, string, time.Time) (model.AccessCredential, error)
	BackendConnections(context.Context, string) ([]model.BackendConnection, error)
	BackendConnection(context.Context, string, string) (model.BackendConnection, error)
	CreateBackendConnection(context.Context, model.BackendConnection) (model.BackendConnection, error)
	UpdateBackendConnection(context.Context, model.BackendConnection, int64) (model.BackendConnection, error)
	SupportRoutes(context.Context, string) ([]model.SupportRoute, error)
	SupportRoute(context.Context, string, string) (model.SupportRoute, error)
	SupportRouteForIntegration(context.Context, string, string) (model.SupportRoute, error)
	SaveSupportRoute(context.Context, model.SupportRoute, int64) (model.SupportRoute, error)
	SetIntegrationSupportRoute(context.Context, string, string, string, string) error
	Products(context.Context, string) ([]model.Product, error)
	CreateProduct(context.Context, model.Product) (model.Product, error)
	Environments(context.Context, string) ([]model.Environment, error)
	CreateEnvironment(context.Context, model.Environment) (model.Environment, error)
	Product(context.Context, string) (model.Product, error)
	UpdateProduct(context.Context, model.Product, int64) (model.Product, error)
	BumpProductCatalogRevision(context.Context, string) (int64, error)
	ProductVersions(context.Context, string) ([]model.ProductVersion, error)
	ProductVersion(context.Context, string, string) (model.ProductVersion, error)
	CreateProductVersion(context.Context, model.ProductVersion) (model.ProductVersion, error)
	UpdateProductVersion(context.Context, model.ProductVersion, int64) (model.ProductVersion, error)
	ProductVersionPins(context.Context, string) ([]model.ProductVersionPin, error)
	ProductVersionPin(context.Context, string, string, string) (model.ProductVersionPin, error)
	SaveProductVersionPin(context.Context, model.ProductVersionPin, int64) (model.ProductVersionPin, error)
	DeleteProductVersionPin(context.Context, string, string) error
	ProductVersionPinHistory(context.Context, string) ([]model.ProductVersionPinHistory, error)
	AppendProductVersionPinHistory(context.Context, model.ProductVersionPinHistory) error
	ProductInstallations(context.Context, string) ([]model.ProductInstallation, error)
	ProductInstallation(context.Context, string, string) (model.ProductInstallation, error)
	ProductInstallationByExternalID(context.Context, string, string) (model.ProductInstallation, error)
	SaveProductInstallation(context.Context, model.ProductInstallation, int64) (model.ProductInstallation, error)
	ProductVersionActivity(context.Context, string, string, time.Time) (model.ProductVersionActivity, error)
	ProductDefinition(context.Context, string) (model.ProductDefinition, error)
	SaveProductDefinition(context.Context, model.ProductDefinition, int64) (model.ProductDefinition, error)
	ProductBuilds(context.Context, string) ([]model.ProductBuild, error)
	ProductBuild(context.Context, string, string) (model.ProductBuild, error)
	CreateProductBuild(context.Context, model.ProductBuild) (model.ProductBuild, error)
	MarkProductBuildPublished(context.Context, string, string) (model.ProductBuild, error)
	Sources(context.Context, string) ([]model.Source, error)
	CreateSource(context.Context, model.Source) (model.Source, error)
	Source(context.Context, string, string) (model.Source, error)
	UpdateSource(context.Context, model.Source, int64) (model.Source, error)
	SourceReview(context.Context, string, string, string) (model.SourceReview, error)
	SourcePublications(context.Context, string, string) ([]model.SourcePublication, error)
	SourcePublication(context.Context, string, string) (model.SourcePublication, error)
	PublishSource(context.Context, string, string, int64, model.SourcePublication, []string) (model.Source, model.SourcePublication, error)
	CrawlJobs(context.Context, string, string) ([]model.CrawlJob, error)
	CreateCrawlJob(context.Context, model.CrawlJob) (model.CrawlJob, error)
	CreateSecret(context.Context, model.Secret) (model.Secret, error)
	Secret(context.Context, string, string) (model.Secret, error)
	Tools(context.Context, string, bool) ([]model.Tool, error)
	Tool(context.Context, string, string) (model.Tool, error)
	CreateTool(context.Context, model.Tool) (model.Tool, error)
	UpdateTool(context.Context, model.Tool, int64) (model.Tool, error)
	RetireTool(context.Context, string, string, int64) (model.Tool, error)
	UpdateImportedTool(context.Context, model.Tool, int64) (model.Tool, error)
	MarkImportedToolDrift(context.Context, string, string, bool) (model.Tool, error)
	PublishTool(context.Context, string, string, int64, string) (model.Tool, error)
	MCPConnections(context.Context, string) ([]model.MCPConnection, error)
	MCPConnection(context.Context, string, string) (model.MCPConnection, error)
	CreateMCPConnection(context.Context, model.MCPConnection) (model.MCPConnection, error)
	UpdateMCPConnectionSync(context.Context, string, string, string, time.Time) (model.MCPConnection, error)
	MCPUserGrant(context.Context, string, string) (model.MCPUserGrant, error)
	SaveMCPUserGrant(context.Context, model.MCPUserGrant) (model.MCPUserGrant, error)
	CreateMCPAuthorizationState(context.Context, model.MCPAuthorizationState) error
	ConsumeMCPAuthorizationState(context.Context, []byte) (model.MCPAuthorizationState, error)
	Providers(context.Context, string) ([]model.Provider, error)
	Provider(context.Context, string, string) (model.Provider, error)
	CreateProvider(context.Context, model.Provider) (model.Provider, error)
	Projects(context.Context, string) ([]model.Project, error)
	Project(context.Context, string, string) (model.Project, error)
	CreateProject(context.Context, model.Project) (model.Project, error)
	CredentialLeases(context.Context, string) ([]model.CredentialLease, error)
	CredentialLease(context.Context, string, string) (model.CredentialLease, error)
	CreateCredentialLease(context.Context, model.CredentialLease) (model.CredentialLease, error)
	RevokeCredentialLease(context.Context, string, string, time.Time) (model.CredentialLease, error)
	IntegrationRuns(context.Context, string) ([]model.IntegrationRun, error)
	IntegrationRun(context.Context, string, string) (model.IntegrationRun, error)
	CreateIntegrationRun(context.Context, model.IntegrationRun) (model.IntegrationRun, error)
	CompleteIntegrationRun(context.Context, string, string, *bool, *bool, string, time.Time) (model.IntegrationRun, error)
	ReportSubmissions(context.Context, string, string, int) ([]model.ReportSubmission, bool, error)
	ReportSubmission(context.Context, string, string) (model.ReportSubmission, error)
	CreateReportSubmission(context.Context, model.ReportSubmission) (model.ReportSubmission, error)
	ActivateHeldReportSubmissions(context.Context, string, string, string, time.Time) error
	ClaimReportSubmissions(context.Context, time.Time, int) ([]model.ReportSubmission, error)
	UpdateReportSubmissionDelivery(context.Context, model.ReportSubmission) (model.ReportSubmission, error)
	RetryReportSubmission(context.Context, string, string, time.Time) (model.ReportSubmission, error)
	DeleteExpiredReportSubmissions(context.Context, time.Time) (int64, error)
	LLMProfiles(context.Context, string) ([]model.LLMProfile, error)
	SaveLLMProfile(context.Context, model.LLMProfile) (model.LLMProfile, error)
	AIProviderConnections(context.Context, string) ([]model.AIProviderConnection, error)
	AIProviderConnection(context.Context, string, string) (model.AIProviderConnection, error)
	SaveAIProviderConnection(context.Context, model.AIProviderConnection, int64) (model.AIProviderConnection, error)
	AIWorkloadProfiles(context.Context, string) ([]model.AIWorkloadProfile, error)
	AIWorkloadProfile(context.Context, string, string) (model.AIWorkloadProfile, error)
	SaveAIWorkloadProfile(context.Context, model.AIWorkloadProfile, int64) (model.AIWorkloadProfile, error)
	ReserveAIBudget(context.Context, model.AIBudgetReservation, int64) (bool, error)
	FinishAIUsage(context.Context, string, model.AIUsageEvent) error
	AIUsageEvents(context.Context, string, time.Time) ([]model.AIUsageEvent, error)
	IntegrationAnalyses(context.Context, string) ([]model.IntegrationAnalysis, error)
	IntegrationAnalysis(context.Context, string, string) (model.IntegrationAnalysis, error)
	SaveIntegrationAnalysis(context.Context, model.IntegrationAnalysis, int64) (model.IntegrationAnalysis, error)
	Recipes(context.Context, string) ([]model.Recipe, error)
	Recipe(context.Context, string, string) (model.Recipe, error)
	RecipeBySlug(context.Context, string, string) (model.Recipe, error)
	SaveRecipe(context.Context, model.Recipe, int64) (model.Recipe, error)
	RecipeRevisions(context.Context, string) ([]model.RecipeRevision, error)
	SaveRecipeRevision(context.Context, model.Recipe, model.RecipeRevision, int64) (model.Recipe, error)
	AIJobs(context.Context, string) ([]model.AIJob, error)
	AIJob(context.Context, string, string) (model.AIJob, error)
	SaveAIJob(context.Context, model.AIJob) (model.AIJob, error)
	Widgets(context.Context, string) ([]model.Widget, error)
	Widget(context.Context, string, string) (model.Widget, error)
	CreateWidget(context.Context, model.Widget) (model.Widget, error)
	UpdateWidget(context.Context, model.Widget, int64) (model.Widget, error)
	CreateWidgetSecret(context.Context, model.WidgetSecret) (model.WidgetSecret, error)
	WidgetSecrets(context.Context, string) ([]model.WidgetSecret, error)
	WidgetSecretByDigest(context.Context, string, []byte) (model.WidgetSecret, error)
	RevokeWidgetSecret(context.Context, string, string, time.Time) (model.WidgetSecret, error)
	CreateWidgetBootstrap(context.Context, model.WidgetBootstrap) error
	WidgetBootstrap(context.Context, []byte) (model.WidgetBootstrap, error)
	ConsumeWidgetBootstrap(context.Context, []byte, time.Time) (model.WidgetBootstrap, error)
	CreateWidgetSession(context.Context, model.WidgetSession) (model.WidgetSession, error)
	WidgetSessions(context.Context, string) ([]model.WidgetSession, error)
	WidgetSessionByDigest(context.Context, []byte, time.Time) (model.WidgetSession, error)
	RevokeWidgetSession(context.Context, string, string, time.Time) (model.WidgetSession, error)
	RevokeWidgetSessions(context.Context, string, time.Time) error
	IdentityProvider(context.Context, string) (identity.ProviderConfig, error)
	SaveIdentityProvider(context.Context, identity.ProviderConfig) (identity.ProviderConfig, error)
	OAuthClient(context.Context, string, string) (identity.OAuthClient, error)
	CreateOAuthClient(context.Context, identity.OAuthClient) (identity.OAuthClient, error)
	CustomerAccounts(context.Context, string, string, int) ([]identity.CustomerAccount, bool, error)
	CustomerAccount(context.Context, string, string) (identity.CustomerAccount, error)
	UpdateCustomerAccount(context.Context, identity.CustomerAccount, int64) (identity.CustomerAccount, error)
	ResolveCustomerAccount(context.Context, identity.CustomerAccount) (identity.CustomerAccount, error)
	CreateOAuthState(context.Context, identity.OAuthState) error
	ConsumeOAuthState(context.Context, []byte) (identity.OAuthState, error)
	CreateOAuthCode(context.Context, identity.OAuthCode) error
	ConsumeOAuthCode(context.Context, []byte) (identity.OAuthCode, error)
	CreateAccessToken(context.Context, identity.AccessToken) error
	AccessTokenByDigest(context.Context, []byte) (identity.AccessToken, error)
	PublicKnowledge(context.Context, string, []string, string) ([]model.KnowledgeRecord, error)
	PrivateKnowledge(context.Context, string, []string, string) ([]model.KnowledgeRecord, error)
	AppendAnalytics(context.Context, model.AnalyticsEvent) error
	AnalyticsSummary(context.Context, string, time.Time) (model.AnalyticsSummary, error)
	RecipePopularity(context.Context, string, time.Time) ([]model.RecipePopularity, error)
	LLMTokensUsed(context.Context, string, string, time.Time) (int64, error)
	AppendAudit(context.Context, model.AuditEvent) error
	AuditEvents(context.Context, string) ([]model.AuditEvent, error)
}
